### ISSUE TITLE
Capybara Webkit driver not working with page_magic

### ISSUE THREAD

**Issue by antmg83** [Ladtech/page_magic#27]
when adding capybara webkit to page_magic
```ruby
NewDriver = PageMagic::Driver.new(:webkit) do
    require 'capybara/webkit/driver'
    Capybara::Webkit::Driver
end
```
The following error is thrown,
```
/usr/local/rvm/rubies/ruby-2.1.1/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /home/agr28/Projects/my-package/test.rb
/usr/local/rvm/gems/ruby-2.1.1@experiment/gems/capybara-webkit-1.7.1/lib/capybara/webkit/driver.rb:48:in `visit': undefined method `visit' for :webkit:Symbol (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.1.1@experiment/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
	from /usr/local/rvm/gems/ruby-2.1.1@experiment/gems/page_magic-1.0.0.alpha8/lib/page_magic/session.rb:30:in `visit'
	from /home/agr28/Projects/my-package/test.rb:30:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

It seems as though adding browser to options in page_magic/driver.rb is unnecessary for this driver

```ruby
def build(app, browser:, options:{})
   options[:browser] = browser
   driver_clazz = handler.call
   driver_clazz.new(app, options)
end
```

**Comment by lashd** [comment]
upgrade to latest pre prerelease version for fix.

The bug was cause by the browser options being defaulted by page_magic. This was required by selenium webdriver, did not affect poltergeist but caused problems with webkit.

Specifying a driver should now be done as follows:
```ruby
Poltergeist = Driver.new(:poltergeist) do |app, options|
    require 'capybara/poltergeist'
    Capybara::Poltergeist::Driver.new(app, options)
end
```

**Comment by lashd** [comment]
This fixed @antmg83 issue.
